"""Contenido de «ENTENDER EL PROYECTO»: un resumen en lenguaje simple de cada módulo del estudio.

Regla: no se inventa información. Cada «¿Qué sabemos hoy?» resume cifras YA escritas en las conclusiones del módulo (archivo
indicado en `docs`) y conserva su clasificación: ESTIMACION (cálculo de un modelo del proyecto), SUPUESTO (hipótesis
registrada), PVDP (dato visto solo en extracto o prensa, sin lectura del original), PENDIENTE (no hay dato). Ninguna cifra
del proyecto está VERIFICADA hoy (DPV-009). «¿Qué es?» y «¿Por qué importa?» son explicaciones generales para un lector
no técnico, sin números nuevos. Los DPV y DEC se leen de los registros centrales (no se redactan aquí).
"""

GRUPOS = {
    "mercado": ("Mercado y clientes", "PROYECTO", "Para quién producir y cuánto se podría vender."),
    "produccion": ("Producción", "PROYECTO", "Pollitos, alimento, granjas y transporte de aves vivas."),
    "planta": ("Planta y procesos", "PROYECTO", "Qué pasa dentro de la planta de faena y con qué equipos."),
    "productos": ("Productos", "PROYECTO", "Qué sale de cada pollo y a dónde puede ir."),
    "localizacion": ("Localización", "PROYECTO", "Dónde podría estar la planta."),
    "logistica": ("Logística", "PROYECTO", "Cómo se mueven aves, alimento, productos y subproductos."),
    "infraestructura": ("Infraestructura", "PROYECTO", "Terreno, edificio, agua, efluentes, energía y frío."),
    "organizacion": ("Organización", "PROYECTO", "Personas, normativa y habilitaciones."),
    "inversion": ("Inversión", "ECONOMIA", "Cuánto hay que invertir (CAPEX) y cómo crecer."),
    "costos": ("Costos", "ECONOMIA", "Costos operativos (OPEX) y capital de trabajo."),
    "finanzas": ("Finanzas", "ECONOMIA", "Rentabilidad: VAN, TIR, payback, fondos."),
    "riesgos": ("Riesgos", "ECONOMIA", "Qué puede salir mal y cómo se elige entre alternativas."),
}

ETIQUETAS_CONFIANZA = {
    "VERIFICADO": "Validado con fuente original",
    "ESTIMACION": "Estimación de un modelo del proyecto",
    "SUPUESTO": "Supuesto de trabajo",
    "PVDP": "Dato externo sin verificar en el original (PVDP)",
    "PENDIENTE": "Pendiente: todavía no hay dato",
}

S, E, P, N = "SUPUESTO", "ESTIMACION", "PVDP", "PENDIENTE"

MODULOS = [
    # ------------------------------------------------------------------ MERCADO
    dict(id="mercado", grupo="mercado", icono="📈", titulo="Mercado avícola", carpeta="01_mercado",
         resumen="Cuánto pollo se produce y consume en Argentina, quién compite y qué pasa con la exportación.",
         que_es="Es el estudio del negocio del pollo en el país: cuánto se produce, cuánto come la gente, quiénes son las empresas grandes y a qué países se exporta.",
         por_que="Define si hay lugar para una empresa nueva y de dónde tendría que salir su crecimiento: en un mercado maduro, crecer significa ganarle participación a otros y vender mejor cada parte del ave.",
         que_modelamos="Una radiografía del mercado argentino e internacional con cifras de fuentes públicas y sectoriales, competidores, exportaciones y sus implicancias para el proyecto (sin dimensionar la planta).",
         que_sabemos=[("Mercado interno grande: ~2,1–2,3 millones de toneladas y ~47–49 kg por habitante por año.", P),
                      ("La faena está estancada en ~740–750 millones de aves por año: un entrante desplaza oferta existente.", P),
                      ("Hay mercados externos reabiertos en 2026 (UE, Japón, Chile, Perú); China sigue sin acceso confirmado.", P),
                      ("Se importan cortes de valor (pechuga, prefritos) a ~2.660 USD/t: hay demanda local de productos de mayor valor.", P),
                      ("Ninguna cifra de mercado se pudo leer en su documento original: son órdenes de magnitud.", N)],
         dpv=["DPV-009", "DPV-010", "DPV-011", "DPV-013", "DPV-016", "DPV-019"], dec=[],
         docs=["01_mercado/conclusiones_mercado.md", "01_mercado/competidores.md"], tablas=["01_mercado/datos_mercado.csv"],
         claves="mercado consumo produccion faena competidores gta granja tres arroyos precios kg habitante"),
    dict(id="demanda", grupo="mercado", icono="🛒", titulo="Clientes y demanda", carpeta="02_clientes_demanda",
         resumen="Quién podría comprar, cuánto y en qué condiciones: supermercados, mayoristas, gastronomía, industria.",
         que_es="Es la estimación de cuánto producto podrían comprar los clientes posibles y cuánto de eso está realmente comprometido.",
         por_que="Sin demanda real no se puede elegir el tamaño de la planta. Que un cliente pueda comprar no significa que la demanda esté asegurada.",
         que_modelamos="Categorías de demanda (A documentada … D potencial), escenarios de prueba de la red de ~90 supermercados y de otros canales, mix de productos, concentración y un cuestionario para validar.",
         que_sabemos=[("La demanda documentada hoy (categorías A + B) es prácticamente nula.", E),
                      ("Escenarios de prueba: conservador 1,5 t/día, base 7,5 t/día y expansivo 23,5 t/día de producto (rango de ~16 veces).", S),
                      ("Los ~90 supermercados podrían representar de 0,25 a 27 t/día según adhesión y kg por local: son canal POTENCIAL, no clientes.", E),
                      ("En los escenarios la red pesaría 57–67 % de las ventas: es el principal riesgo de concentración.", E),
                      ("La exportación no es demanda hoy (niveles 0–2): entra como opción de diseño.", S)],
         dpv=["DPV-002", "DPV-003", "DPV-004", "DPV-018", "DPV-020", "DPV-036", "DPV-037", "DPV-038", "DPV-039", "DPV-040"], dec=["DEC-019"],
         docs=["02_clientes_demanda/conclusiones_demanda.md", "02_clientes_demanda/supermercados.md", "02_clientes_demanda/cuestionario_supermercados.md"],
         tablas=["02_clientes_demanda/escenarios_demanda.csv"],
         claves="demanda clientes supermercados 90 red mayoristas gastronomia industria carniceria canal concentracion mix"),
    dict(id="exportacion", grupo="mercado", icono="🚢", titulo="Exportación", carpeta="17_exportacion",
         resumen="Qué partes del pollo se venden afuera, a qué países y qué exige cada destino.",
         que_es="Es vender productos avícolas a otros países. Cada destino tiene su propio permiso sanitario, sus requisitos de planta y sus preferencias por partes del pollo.",
         por_que="Algunas partes valen poco en Argentina y más afuera (garras, menudencias): exportarlas sube el ingreso total por ave. Pero exige habilitaciones, escala y capital de trabajo.",
         que_modelamos="Comercio mundial por producto, acceso por país (habilitado / se exporta / potencial / cerrado), requisitos de planta exportadora, Halal, logística y estrategia de valorización del ave.",
         que_sabemos=[("Países con apertura posterior a feb-2026: UE, Japón, Corea del Sur, Chile, Perú. China: sin acceso confirmado.", P),
                      ("País abierto ≠ planta habilitada ≠ producto autorizado: una planta nueva necesita su propio listado por destino.", P),
                      ("Precios por producto de cientos de USD/t (harinas, CMS) a ~3.500 USD/t (garras CIF China): preliminares, no aptos para calcular rentabilidad.", P),
                      ("Criterio: comparar el «net-back» en planta (precio menos costos hasta destino), no el precio en USD/t.", E),
                      ("Demanda de exportación del proyecto = 0 (sin compradores).", N)],
         dpv=["DPV-015", "DPV-024", "DPV-026", "DPV-030", "DPV-034", "DPV-035"], dec=["DEC-009"],
         docs=["17_exportacion/conclusiones_exportacion.md", "17_exportacion/estrategia_valorizacion_ave.md"], tablas=["17_exportacion/datos_exportacion.csv"],
         claves="exportacion halal china ue japon vietnam chile contenedor puerto destino garras"),
    # ------------------------------------------------------------------ PRODUCCIÓN
    dict(id="produccion", grupo="produccion", icono="🐔", titulo="Producción de pollos (crianza)", carpeta="03_produccion_primaria",
         resumen="Cómo un pollito de un día se convierte en un pollo listo para faenar.",
         que_es="La crianza o engorde: el pollito BB llega a un galpón, come alimento durante ~45–50 días y sale con ~2,7–3,0 kg de peso vivo.",
         por_que="Es donde se gasta la mayor parte del costo (el alimento) y donde se decide cuántos pollitos, cuánto alimento y cuántos galpones hacen falta.",
         que_modelamos="Ciclo productivo, rangos de peso, edad, conversión alimenticia (FCR) y mortalidad, densidad, galpones, bioseguridad y 72 escenarios físicos (2.500–20.000 aves faenadas por día).",
         que_sabemos=[("Para faenar 10.000 aves/día (5 días/semana) hacen falta ~52.800 pollitos BB por semana plena.", E),
                      ("Perfil medio: ~4,6–5,4 kg de alimento por ave faenada; +0,1 de FCR = +5,9 % de alimento.", E),
                      ("Con 47 días de crianza salen ~5,7 lotes por año en un galpón (no 365 ÷ 47).", E),
                      ("Escenario medio de 10.000 aves/día: ~37.900 m² de galpón (≈ 16 galpones de 2.400 m²).", E),
                      ("Un estudio de Entre Ríos reporta mortalidades de 7,7–9,5 %, por encima del 5 % supuesto: señal a validar.", P)],
         dpv=["DPV-019", "DPV-044", "DPV-045", "DPV-048", "DPV-051"], dec=["DEC-020", "DEC-024"],
         docs=["03_produccion_primaria/guia_ramiro.md", "03_produccion_primaria/conclusiones_produccion.md", "03_produccion_primaria/ciclo_productivo.md"],
         tablas=["03_produccion_primaria/escenarios_produccion.csv"],
         claves="produccion crianza engorde fcr conversion mortalidad peso edad galpon pollitos bioseguridad ciclo"),
    dict(id="incubacion", grupo="produccion", icono="🥚", titulo="Incubación y pollitos", carpeta="15_incubacion",
         resumen="De dónde salen los pollitos BB: comprarlos o incubar huevo fértil.",
         que_es="La incubación convierte huevos fértiles en pollitos de un día (21 días en máquinas incubadoras y nacedoras). Se puede comprar el pollito a una incubadora o tener incubadora propia.",
         por_que="Sin pollitos no hay producción. Es un insumo concentrado en pocos proveedores; incubar propio cambia la dependencia del pollito por la del huevo fértil.",
         que_modelamos="Demanda de pollitos y huevos por escala, tiempos de incubación, capacidad de máquinas (setter/hatcher) según cadencia de nacimientos y comparación compra vs incubación vs reproductoras.",
         que_sabemos=[("Demanda (medio, 5 d): 13.197 / 26.395 / 52.790 / 105.580 pollitos por semana plena para 2.500 / 5.000 / 10.000 / 20.000 aves/día.", E),
                      ("Incubación de 21 días (18 + 3); del huevo a la faena pasan al menos 71–75 días.", E),
                      ("Opción incubación: ~1,24 huevos recibidos por pollito vendible.", E),
                      ("Incubadora propia y reproductoras solo aparecen en las arquitecturas C3 y CF (futura).", S)],
         dpv=["DPV-006", "DPV-047", "DPV-133", "DPV-153", "DPV-154"], dec=["DEC-023"],
         docs=["15_incubacion/guia_ramiro.md", "15_incubacion/conclusiones_incubacion.md"], tablas=[],
         claves="incubacion pollito bb huevo fertil incubadora reproductoras setter hatcher nacimiento"),
    dict(id="alimento", grupo="produccion", icono="🌽", titulo="Alimento balanceado", carpeta="14_alimento_balanceado",
         resumen="Cuánto alimento hace falta y si conviene comprarlo, hacerlo a façon o tener planta propia.",
         que_es="El alimento balanceado es la mezcla (sobre todo maíz y harina de soja) que comen los pollos. Se puede comprar hecho, encargar su fabricación (façon) o fabricarlo en una planta propia.",
         por_que="Es el mayor costo y el mayor flujo físico del negocio: mueve más toneladas que cualquier otra cosa.",
         que_modelamos="Demanda de alimento por escala, planta conceptual, silos e inventarios por propiedad, y la comparación compra / façon (con materias primas propias o del elaborador) / planta propia, sin elegir.",
         que_sabemos=[("Alimento: 3.091 / 6.181 / 12.362 / 24.724 t por año para 2.500 / 5.000 / 10.000 / 20.000 aves/día (medio).", E),
                      ("Maíz + harina de soja ≈ 85–95 % del tonelaje (la fórmula es del nutricionista).", E),
                      ("Entregas: 3 / 5 / 9 / 18 camiones de 28 t por semana según escala.", E),
                      ("La demanda física es la misma en compra o integración: cambia quién es dueño del stock.", E),
                      ("Precio del alimento puesto en granja: PENDIENTE.", N)],
         dpv=["DPV-050", "DPV-155", "DPV-156", "DPV-157", "DPV-158"], dec=["DEC-024", "DEC-074"],
         docs=["14_alimento_balanceado/guia_ramiro.md", "14_alimento_balanceado/conclusiones_alimento.md"], tablas=[],
         claves="alimento balanceado maiz soja facon planta de alimento silos granos nutricion"),
    dict(id="granjas", grupo="produccion", icono="🏠", titulo="Granjas", carpeta="03_produccion_primaria",
         resumen="Quién cría los pollos: granjas propias, productores integrados o compra de pollo vivo.",
         que_es="Las granjas son los galpones donde se crían los pollos. En la «integración», un productor pone el galpón y la mano de obra y la empresa pone el pollito y el alimento.",
         por_que="Decide cuánto capital hay que poner en galpones, cuánto control se tiene sobre la calidad y la sanidad, y cuánto capital de trabajo se inmoviliza.",
         que_modelamos="Modelos de abastecimiento (propio / integrado / compra / mixto), galpones, bioseguridad, energía de respaldo y el chequeo de sincronización entre lotes de nacimiento, galpones y faena.",
         que_sabemos=[("La integración es el modelo dominante del sector: traslada el costo de los galpones al productor.", P),
                      ("En el escenario medio de 10.000 aves/día, un ciclo de crianza inmoviliza ~1.660 t de alimento.", E),
                      ("Granjas equivalentes de 30.000 plazas: 4 / 8 / 16 / 32 según escala.", E),
                      ("Un galpón cerrado depende 100 % de la electricidad: el respaldo es un requisito.", P),
                      ("Disponibilidad real de productores integrables: PENDIENTE.", N)],
         dpv=["DPV-044", "DPV-048", "DPV-049", "DPV-051", "DPV-170"], dec=["DEC-020"],
         docs=["03_produccion_primaria/modelos_integracion.md", "03_produccion_primaria/galpones.md", "03_produccion_primaria/bioseguridad.md"], tablas=[],
         claves="granjas galpones integrados integracion productores propias bioseguridad m2 plazas"),
    dict(id="transporte_vivo", grupo="produccion", icono="🚚", titulo="Transporte de aves vivas", carpeta="13_logistica",
         resumen="Cómo llegan los pollos de la granja a la planta: captura, carga, viaje y espera.",
         que_es="Antes de faenar, los pollos se retiran del alimento, se capturan, se cargan en jaulas y viajan en camión a la planta. Ese tramo afecta el bienestar animal, la mortalidad y el peso.",
         por_que="Limita qué tan lejos pueden estar las granjas de la planta y cuántos camiones hacen falta por día.",
         que_modelamos="La ventana previa a la faena tramo por tramo, viajes por escala, alcance de transporte bajo la parametrización actual y la habilitación de vehículos (Res. SENASA 723/2025).",
         que_sabemos=[("Aves cargadas: 2.508 / 5.015 / 10.030 / 20.060 por día (7,3 / 14,5 / 29,1 / 58,2 t vivas).", E),
                      ("Con 5.500 aves por camión (escenario): 1 / 1–2 / 2–3 / 4–5 viajes por día según escala y estación.", S),
                      ("Con una ventana de 10 h (escenario) queda ~4,5 h de viaje disponible: es un resultado del modelo, no un límite legal.", S),
                      ("Capacidad real de los camiones: no validada ni cotizada.", N)],
         dpv=["DPV-058", "DPV-084", "DPV-127", "DPV-133"], dec=[],
         docs=["13_logistica/logistica_aves_vivas.md", "03_produccion_primaria/transporte_aves.md"], tablas=[],
         claves="transporte aves vivas captura camion jaulas ayuno doa bienestar ventana prefaena"),
    # ------------------------------------------------------------------ PLANTA
    dict(id="faena", grupo="planta", icono="🏭", titulo="Planta de faena", carpeta="05_proceso_industrial",
         resumen="La planta donde el pollo vivo se convierte en carne refrigerada o congelada.",
         que_es="El frigorífico avícola: recibe aves vivas, las faena, las enfría, las trocea, las empaca y las guarda en frío hasta despacharlas.",
         por_que="Es la inversión central de casi todas las arquitecturas (salvo C0) y define la capacidad del negocio.",
         que_modelamos="El flujo completo en 32 etapas, capacidades horarias por escala, cuellos de botella, zonificación higiénica, automatización por escala y la ecuación de las 24 horas.",
         que_sabemos=[("Ritmo con 8 h netas: 312 / 625 / 1.250 / 2.500 aves por hora para 2.500 / 5.000 / 10.000 / 20.000 aves/día.", E),
                      ("Capacidad nominal ≠ garantizada ≠ operativa ≠ real: la capacidad contractual es un dato crítico de cotización.", S),
                      ("16 h netas (dos turnos) son una restricción severa de calendario que debe validarse antes de descartar.", E),
                      ("No hay umbral fijo para pasar de evisceración manual a automática: depende de cotizaciones y productividad real.", P)],
         dpv=["DPV-090", "DPV-097", "DPV-061"], dec=["DEC-036"],
         docs=["05_proceso_industrial/guia_ramiro.md", "05_proceso_industrial/conclusiones_proceso.md"], tablas=["05_proceso_industrial/capacidad_proceso.csv"],
         claves="planta faena frigorifico proceso capacidad aves hora turnos linea"),
    dict(id="proceso", grupo="planta", icono="⚙️", titulo="Proceso industrial", carpeta="05_proceso_industrial",
         resumen="Las etapas dentro de la planta, en orden, desde la recepción hasta el despacho.",
         que_es="Es la secuencia de operaciones: recibir aves, colgarlas, aturdirlas, desangrarlas, escaldarlas, desplumarlas, eviscerarlas, inspeccionarlas, enfriarlas, clasificarlas, trozarlas, empacarlas y guardarlas en frío.",
         por_que="Cada etapa tiene equipos, personas, agua, energía y riesgos de inocuidad. El orden «sucio → limpio → frío» no se puede romper.",
         que_modelamos="Las etapas E01–E32 con función, control, riesgo y salidas laterales (kg/ave), puntos de inspección y flujos de subproductos.",
         que_sabemos=[("32 etapas desde la recepción hasta el despacho, más la sala de garras, menudencias y carcasa.", E),
                      ("A 10.000 aves/día entran ~3.625 kg/h de pollo vivo y salen ~2.996 kg/h de comestible a empaque.", E),
                      ("Enfriamiento: punto crítico de inocuidad y posible cuello de botella; límite de agua absorbida a verificar (~8 %).", P)],
         dpv=["DPV-061", "DPV-090"], dec=["DEC-026", "DEC-027"],
         docs=["05_proceso_industrial/flujo_proceso.md", "05_proceso_industrial/zonificacion_higienica.md"], tablas=[],
         claves="proceso faena colgado aturdido sangrado escaldado desplume eviscerado inspeccion enfriamiento chiller trozado empaque"),
    dict(id="maquinaria", grupo="planta", icono="🔧", titulo="Maquinaria", carpeta="08_maquinaria",
         resumen="Qué equipos necesita cada etapa y cómo se van a cotizar (sin elegir proveedor).",
         que_es="El catálogo de equipos de la planta: transportadores, aturdidores, escaldadoras, desplumadoras, evisceradoras, enfriadores, trozadoras, envasadoras, túneles y cámaras.",
         por_que="Define buena parte de la inversión, la capacidad real y la necesidad de personal. En esta fase no se elige proveedor.",
         que_modelamos="76 equipos conceptuales en 9 grupos, automatización por escala, proveedores preliminares (nacionales e importados) y un plan de cotización uniforme (RFQ, no enviado).",
         que_sabemos=[("76 equipos conceptuales con alternativas, criticidad, redundancia y servicios.", S),
                      ("Benchmarks de fabricante (BAADER CP396, Meyn LEAP, JBT Marel/Calisa2) leídos por el promotor; no son especificación del proyecto.", P),
                      ("Ninguna cotización solicitada todavía: precios de equipos PENDIENTES.", N)],
         dpv=["DPV-097", "DPV-088", "DPV-089"], dec=["DEC-049"],
         docs=["08_maquinaria/README.md", "08_maquinaria/catalogo_equipos.md", "08_maquinaria/automatizacion_por_escala.md"], tablas=["08_maquinaria/matriz_equipos.csv"],
         claves="maquinaria equipos proveedores rfq cotizacion baader meyn marel automatizacion"),
    dict(id="frio", grupo="infraestructura", icono="❄️", titulo="Frío y congelado", carpeta="12_energia_frio",
         resumen="Enfriar, congelar y guardar el producto sin cortar la cadena de frío.",
         que_es="El sistema de refrigeración enfría las carcasas, mantiene las salas de corte frías, congela el producto que no se vende fresco y lo guarda en cámaras.",
         por_que="Sin frío no hay producto vendible. El perfil refrigerado/congelado cambia más el tamaño del frío que la escala.",
         que_modelamos="Carga sensible del producto, congelación y almacenamiento separados, refrigerantes comparados sin elegir y respaldo.",
         que_sabemos=[("Carga sensible del producto: 25 / 50 / 99 / 198 kWf en 8 h por escala (no es la capacidad total de la planta).", E),
                      ("Congelación (perfil P1): 0,6 / 1,2 / 2,4 / 4,8 t nuevas por día; con P3, 5 veces más.", E),
                      ("Carga frigorífica total: PENDIENTE (requiere balance del proveedor).", N)],
         dpv=["DPV-109"], dec=["DEC-045"],
         docs=["12_energia_frio/conclusiones_energia_frio.md", "12_energia_frio/sistema_frio.md"], tablas=[],
         claves="frio refrigeracion congelado camaras tunel amoniaco cadena de frio"),
    # ------------------------------------------------------------------ PRODUCTOS
    dict(id="balance", grupo="productos", icono="⚖️", titulo="Balance de masa", carpeta="04_balance_masa",
         resumen="Cuántos kilos de cada parte salen de un pollo vivo.",
         que_es="Es la cuenta de cuántos gramos de pechuga, pata-muslo, alas, menudencias, plumas, sangre, etc. salen de un pollo de 2,9 kg.",
         por_que="Convierte aves en toneladas de producto vendible: sin él no se puede pasar de demanda a escala ni de precios a ingresos.",
         que_modelamos="Balance por ave para 6 pesos, cortes y deshuese, menudencias, garras, subproductos, agua del enfriamiento, condenas y 3 configuraciones de producto.",
         que_sabemos=[("Carcasa eviscerada ≈ 71,5 % del peso vivo a 2,9 kg (escenario medio).", E),
                      ("Pechuga con hueso ≈ 0,784 kg por ave; pata-muslo ≈ 0,631; alas ≈ 0,208 (2,9 kg, medio).", E),
                      ("Ningún rendimiento proviene de una planta argentina: falta un ensayo en planta.", N)],
         dpv=["DPV-059", "DPV-060", "DPV-065"], dec=["DEC-028"],
         docs=["04_balance_masa/guia_ramiro.md", "04_balance_masa/conclusiones_balance.md"], tablas=["04_balance_masa/escenarios_balance.csv"],
         claves="balance masa rendimiento kg por ave cortes carcasa"),
    dict(id="productos", grupo="productos", icono="🍗", titulo="Productos", carpeta="06_productos",
         resumen="Pollo entero, cortes, deshuesados y elaborados: qué se puede vender.",
         que_es="El catálogo de lo que la empresa podría vender: entero, trozado, deshuesado, menudencias, garras y elaborados (milanesas, hamburguesas, etc.).",
         por_que="El objetivo económico es vender cada parte del pollo donde más paga (ingreso total por ave), no vender la mayor cantidad de pollo entero.",
         que_modelamos="Matriz de 30 productos con materia prima, kg por ave, nivel de procesamiento, frío, vida útil, canales y requisitos de exportación.",
         que_sabemos=[("Productos de mayor valor potencial: suprema y solomillo, muslo deshuesado, milanesas y listos para cocinar.", E),
                      ("Toda la demanda de productos es no validada (categorías C/D).", N),
                      ("Precios por producto: PENDIENTES (ningún precio con evidencia E1–E3).", N)],
         dpv=["DPV-013", "DPV-037", "DPV-070", "DPV-078"], dec=["DEC-005", "DEC-030"],
         docs=["06_productos/catalogo_productos.md", "06_productos/elaborados.md"], tablas=["06_productos/matriz_productos.csv"],
         claves="productos pechuga suprema pata muslo alas entero trozado deshuesado milanesas elaborados"),
    dict(id="subproductos", grupo="productos", icono="♻️", titulo="Subproductos y rendering", carpeta="07_subproductos",
         resumen="Plumas, sangre, vísceras, cabezas y huesos: venderlos, procesarlos o pagar para que se los lleven.",
         que_es="Son las partes no comestibles. Pueden venderse a terceros, transformarse en harinas y grasas (rendering) o convertirse en un costo si no hay comprador.",
         por_que="Son ~15–20 % del peso del ave, salen todos los días y son perecederos: sin un destino resuelto la planta no puede operar.",
         que_modelamos="Mapa de 39 salidas del ave, rutas de valorización (venta directa, rendering propio o tercerizado, pet food), 15 incompatibilidades entre rutas y escalado.",
         que_sabemos=[("Plumas húmedas ≈ 0,241 kg/ave: el mayor subproducto en masa.", E),
                      ("Recuperar la sangre reduce mucho la carga del efluente.", P),
                      ("A 2.500–5.000 aves/día el problema es conseguir un receptor; a 20.000 se vuelve pertinente el rendering propio (no decidido).", E),
                      ("Compradores y precios de subproductos: PENDIENTES.", N)],
         dpv=["DPV-065", "DPV-066", "DPV-072"], dec=["DEC-027", "DEC-029", "DEC-031"],
         docs=["07_subproductos/guia_ramiro.md", "07_subproductos/conclusiones_valorizacion.md"], tablas=["07_subproductos/matriz_valorizacion.csv"],
         claves="subproductos rendering plumas sangre visceras cabezas huesos harinas cms carcasa garras"),
    # ------------------------------------------------------------------ LOCALIZACIÓN
    dict(id="localizacion", grupo="localizacion", icono="📍", titulo="Localización", carpeta="10_localizacion",
         resumen="Dónde podría estar la planta: 13 corredores en 5 provincias evaluados con criterios explícitos.",
         que_es="Es la búsqueda de la mejor zona para la planta, mirando granjas, granos, mercado, rutas, agua, energía, normativa y personal.",
         por_que="La ubicación fija costos de todos los días (fletes, agua, efluentes, energía) y la relación con productores y clientes.",
         que_modelamos="Una matriz multicriterio (13 corredores × 48 subcriterios en 14 grupos + 3 compensaciones), 4 perfiles de ponderación, gates duros y condicionales y una ficha de relevamiento de terrenos.",
         que_sabemos=[("Todavía no existe una ubicación ganadora porque faltan datos de campo.", N),
                      ("De 624 celdas de la matriz: 0 verificadas, 35 con datos de extractos o estimados y 589 vacías.", E),
                      ("Ninguna región alcanza la cobertura mínima de información (60, 75 ni 90 %): no se emite ranking.", E),
                      ("El contacto en Chaco es una ventaja cualitativa de acceso, no un criterio de ubicación.", S)],
         dpv=["DPV-053", "DPV-087", "DPV-095", "DPV-106", "DPV-141"], dec=["DEC-003", "DEC-051", "DEC-052", "DEC-053"],
         docs=["10_localizacion/guia_ramiro.md", "10_localizacion/conclusiones_localizacion.md", "10_localizacion/regiones_preliminares.md"],
         tablas=["10_localizacion/matriz_localizacion.csv", "10_localizacion/resultados_localizacion.csv"],
         claves="localizacion ubicacion donde zona region corredor provincia buenos aires entre rios santa fe cordoba chaco terreno gates"),
    # ------------------------------------------------------------------ LOGÍSTICA
    dict(id="logistica", grupo="logistica", icono="🛣️", titulo="Logística de producto", carpeta="13_logistica",
         resumen="Cómo llega el producto a los clientes: refrigerado, congelado, directo o vía centro de distribución.",
         que_es="Todo lo que se mueve: alimento a las granjas, aves a la planta, producto a los clientes, subproductos a sus receptores y contenedores a puerto.",
         por_que="El costo logístico por kg puede cambiar más el margen que el precio, sobre todo si hay que entregar a muchos locales chicos.",
         que_modelamos="Modelo físico de todos los flujos, refrigerado vs congelado, distribución directa vs centro de distribución, flota propia vs tercerizada, inventarios y KPI (sin costos).",
         que_sabemos=[("Comestible: 6,0 / 12,0 / 24,0 / 47,9 t por día de faena según escala (configuración B).", E),
                      ("Con la parametrización actual, la distribución directa desde lejos del AMBA es mucho menos eficiente que consolidar en un CD.", S),
                      ("Subproductos a retirar: 1,5 / 3,0 / 6,1 / 12,2 t/día (configuración B).", E),
                      ("Costos de flete, transportistas y capacidades reales: PENDIENTES.", N)],
         dpv=["DPV-036", "DPV-042", "DPV-054", "DPV-084", "DPV-116"], dec=["DEC-016", "DEC-055"],
         docs=["13_logistica/guia_ramiro.md", "13_logistica/conclusiones_logistica.md"], tablas=[],
         claves="logistica distribucion flete camiones refrigerado congelado cd centro de distribucion flota contenedores"),
    # ------------------------------------------------------------------ INFRAESTRUCTURA
    dict(id="layout", grupo="infraestructura", icono="📐", titulo="Layout, edificio y terreno", carpeta="09_layout_obra_civil",
         resumen="Qué áreas necesita la planta, cuántos m² y qué tamaño de terreno.",
         que_es="El programa de áreas del edificio (salas de proceso, frío, servicios, vestuarios, oficinas) y cómo se ordenan para que lo sucio nunca cruce con lo limpio.",
         por_que="Define la obra civil, el terreno a buscar y cómo se puede crecer sin rehacer la planta.",
         que_modelamos="54 áreas en 9 zonas, 9 flujos, superficies por escala, terreno conceptual y estrategia de expansión (sin planos).",
         que_sabemos=[("Superficie construida (medio): ~1.780 / 2.600 / 4.310 / 7.450 m² para 2.500 / 5.000 / 10.000 / 20.000 aves/día.", E),
                      ("Terreno conceptual (medio): ~2,0 / 2,3 / 3,1 / 4,4 ha, o ~3,3 ha reservando desde el inicio para 20.000.", E),
                      ("El edificio ocupa ~10–17 % del terreno; retiros reales y footprints de proveedores: PENDIENTES.", E)],
         dpv=["DPV-115", "DPV-141", "DPV-087"], dec=["DEC-063"],
         docs=["09_layout_obra_civil/guia_ramiro.md", "09_layout_obra_civil/conclusiones_layout.md"], tablas=[],
         claves="layout terreno obra civil edificio superficie m2 hectareas zonas expansion"),
    dict(id="agua", grupo="infraestructura", icono="💧", titulo="Agua y efluentes", carpeta="11_agua_efluentes",
         resumen="Cuánta agua usa la planta y qué hay que hacer con el agua sucia que sale.",
         que_es="La planta usa mucha agua (escaldado, lavado, enfriamiento, limpieza) y devuelve agua con sangre, grasa y restos orgánicos que hay que tratar antes de volcarla.",
         por_que="El agua disponible y el permiso de vuelco pueden fijar la escala posible de un sitio.",
         que_modelamos="Balance de cinco aguas, carga orgánica por dos métodos, alternativas de tratamiento y masa segregable en origen (modelo de sensibilidad, no diseño).",
         que_sabemos=[("Agua utilizada (sensibilidad): 15 / 25 / 38 L por ave → ~62 / 125 / 250 / 500 m³/día (medio) según escala.", E),
                      ("Con un límite de ejemplo de 250 mg/L de DQO, el escenario medio exigiría ~95 % de remoción.", P),
                      ("Lodos, sólidos al efluente y tecnología de tratamiento: PENDIENTES.", N)],
         dpv=["DPV-053", "DPV-067", "DPV-103", "DPV-108"], dec=["DEC-043"],
         docs=["11_agua_efluentes/guia_ramiro.md", "11_agua_efluentes/conclusiones_agua_efluentes.md"], tablas=[],
         claves="agua efluentes tratamiento vuelco dqo lagunas perforacion lodos"),
    dict(id="energia", grupo="infraestructura", icono="⚡", titulo="Energía", carpeta="12_energia_frio",
         resumen="Electricidad y gas para la planta y las granjas, y respaldo ante cortes.",
         que_es="La planta consume electricidad (motores, frío, iluminación) y calor (escaldado, limpieza). Las granjas necesitan electricidad continua para ventilar.",
         por_que="La potencia disponible y la calidad de la red pueden decidir un sitio; un corte puede matar aves o romper la cadena de frío.",
         que_modelamos="Energía diaria por ave, potencia media equivalente, calor útil y carga crítica ilustrativa (los picos y el generador quedan pendientes).",
         que_sabemos=[("~0,8 kWh por ave → ~2.046 / 4.092 / 8.184 / 16.368 kWh por día operativo según escala (medio).", E),
                      ("~1 MJ útil por ave → ~343 m³/día de gas equivalente a 10.000 aves/día.", E),
                      ("Potencia pico, transformador y grupo electrógeno: PENDIENTES (requieren lista de cargas).", N)],
         dpv=["DPV-052", "DPV-095"], dec=["DEC-045", "DEC-046"],
         docs=["12_energia_frio/conclusiones_energia_frio.md", "12_energia_frio/demanda_energia.md"], tablas=[],
         claves="energia electricidad gas potencia kw kwh generador respaldo cortes"),
    # ------------------------------------------------------------------ ORGANIZACIÓN
    dict(id="rrhh", grupo="organizacion", icono="👥", titulo="Recursos humanos", carpeta="18_recursos_humanos",
         resumen="Cuántas personas, en qué puestos y turnos, según la escala.",
         que_es="La organización de la empresa: puestos de producción, limpieza, mantenimiento, calidad, logística, administración y dirección.",
         por_que="El personal es un costo fijo importante y una restricción: hay tareas manuales (colgado, evisceración) que dependen de conseguir gente.",
         que_modelamos="Estructura funcional, organigramas, dotación por escala en unidades separadas (puestos, simultáneos, pico en sitio, FTE), turnos y productividad.",
         que_sabemos=[("FTE internos (medio): ~55 / 77 / 99 / 126 para 2.500 / 5.000 / 10.000 / 20.000 aves/día.", E),
                      ("Pico de personas en sitio (medio): ~41 / 58 / 72 / 87.", E),
                      ("Headcount de nómina y salarios: PENDIENTES (plantilla de costo laboral vacía).", N)],
         dpv=["DPV-146", "DPV-147", "DPV-148", "DPV-150"], dec=["DEC-067"],
         docs=["18_recursos_humanos/guia_ramiro.md", "18_recursos_humanos/conclusiones_rrhh.md"], tablas=[],
         claves="rrhh personal recursos humanos fte dotacion turnos salarios organigrama"),
    dict(id="normativa", grupo="organizacion", icono="📜", titulo="Normativa y habilitaciones", carpeta="16_normativa_senasa",
         resumen="Qué permisos hacen falta desde el terreno hasta exportar.",
         que_es="La planta necesita permisos municipales, provinciales (ambiente, agua) y de SENASA (habilitación sanitaria, inspección veterinaria permanente, registro de productos).",
         por_que="Sin habilitación no se puede vender; el nivel de habilitación (provincial, federal, exportación) define a qué mercados se llega.",
         que_modelamos="Mapa de autoridades, ruta de habilitación, 64 requisitos en una matriz regulatoria, programas sanitarios y preguntas para SENASA (no es asesoramiento jurídico).",
         que_sabemos=[("Cadena de cuatro niveles: local → SENASA tránsito federal → autorización por destino → aceptación del importador.", P),
                      ("El plan APPCC/HACCP es obligatorio para establecimientos SENASA, también para el mercado interno.", P),
                      ("Ninguna norma leída en su original: 0 datos verificados.", N)],
         dpv=["DPV-007", "DPV-046", "DPV-061", "DPV-090"], dec=["DEC-009"],
         docs=["16_normativa_senasa/guia_ramiro.md", "16_normativa_senasa/conclusiones_normativa.md"], tablas=["16_normativa_senasa/matriz_regulatoria.csv"],
         claves="normativa senasa habilitacion permisos haccp appcc decreto 4238 transito federal municipio"),
    # ------------------------------------------------------------------ ECONOMÍA
    dict(id="capex", grupo="inversion", icono="🏗️", titulo="Inversión (CAPEX)", carpeta="19_capex",
         resumen="Qué activos hay que comprar o construir en cada arquitectura y escala.",
         que_es="CAPEX es la inversión en activos: terreno, edificio, máquinas, frío, utilities, galpones, etc.",
         por_que="Define cuánto capital inicial hace falta. Pero el capital necesario es mayor: hay que sumar capital de trabajo y las pérdidas del arranque.",
         que_modelamos="Un motor que arma la lista de activos (BOQ) de cada configuración y escala, con 175 conceptos de costo, capas de importación e instalación y plan de cotizaciones.",
         que_sabemos=[("No existe todavía un CAPEX total para ninguna configuración: 167 de 175 conceptos no tienen precio.", N),
                      ("Los 8 conceptos con precio son de prensa o web (E4, sin verificar).", P),
                      ("Sí se sabe qué activos requiere cada arquitectura y en qué paquete se cotizan.", E),
                      ("Ninguna comparación contra USD 2 M es posible: con 1–2 % de cobertura no se puede afirmar que alcanza ni que no alcanza.", E)],
         dpv=["DPV-086", "DPV-093", "DPV-097", "DPV-161", "DPV-167"], dec=["DEC-010", "DEC-063"],
         docs=["19_capex/guia_ramiro.md", "19_capex/conclusiones_capex.md"], tablas=["19_capex/escenarios_capex.csv"],
         claves="capex inversion activos boq cotizaciones usd 2 millones equipos obra"),
    dict(id="opex", grupo="costos", icono="🧾", titulo="Costos operativos (OPEX)", carpeta="20_opex",
         resumen="Qué cuesta operar: alimento, pollitos, personal, energía, agua, fletes, mantenimiento.",
         que_es="OPEX son los costos de funcionamiento de todos los meses: insumos, servicios, sueldos, mantenimiento.",
         por_que="Junto con los precios de venta determinan si cada pollo deja margen.",
         que_modelamos="Un motor con 359 conceptos de costo por arquitectura, quién aporta cada costo (empresa, productor, tercero), naturaleza fija/variable y completitud por módulo.",
         que_sabemos=[("No existe todavía un OPEX total ni un costo por ave: ninguna arquitectura es costeable.", N),
                      ("Solo 2 conceptos tienen precio (pollito BB y maíz), ambos de fuentes no verificadas.", P),
                      ("Se sabe qué costos existen en cada arquitectura (cobertura estructural 100 %).", E)],
         dpv=["DPV-050", "DPV-052", "DPV-148", "DPV-172", "DPV-175"], dec=["DEC-088"],
         docs=["20_opex/guia_ramiro.md", "20_opex/conclusiones_opex.md"], tablas=["20_opex/completitud_arquitecturas_opex.csv"],
         claves="opex costos operativos alimento pollito salarios energia mantenimiento costo por ave"),
    dict(id="capital_trabajo", grupo="costos", icono="💼", titulo="Capital de trabajo", carpeta="20_opex",
         resumen="El dinero inmovilizado en stock y en cuentas por cobrar mientras el negocio funciona.",
         que_es="Es la plata que hay que tener puesta para operar: alimento y aves en crianza, producto en cámaras y lo que los clientes todavía no pagaron, menos lo que se debe a proveedores.",
         por_que="Con producto perecedero y clientes que pagan a plazo, puede ser grande; el pico de fondos del proyecto incluye este dinero.",
         que_modelamos="Inventarios propios vs de terceros por arquitectura, cuentas por cobrar y por pagar, caja operativa (sin valores económicos todavía).",
         que_sabemos=[("CAPITAL_TRABAJO = PENDIENTE en todos los escenarios: faltan precios, días de cobro y de pago.", N),
                      ("Solo entra el stock que es propiedad de la empresa; en façon depende del contrato.", S)],
         dpv=["DPV-175"], dec=["DEC-089", "DEC-091"],
         docs=["20_opex/capital_trabajo.md"], tablas=["20_opex/capital_trabajo_opex.csv"],
         claves="capital de trabajo inventarios stock cuentas por cobrar dias de cobro dias de pago caja"),
    dict(id="finanzas", grupo="finanzas", icono="💰", titulo="Modelo financiero", carpeta="21_modelo_financiero",
         resumen="Cómo se calcula la rentabilidad: ingresos, costos, inversión, flujo de caja, VAN, TIR y payback.",
         que_es="Es el modelo que une todo: demanda → producción → ventas → costos → resultado → flujo de caja → indicadores de rentabilidad.",
         por_que="Es el que responde «¿conviene?»… cuando haya datos. Hoy dice qué falta para poder responder.",
         que_modelamos="Un motor mensual con modos EVIDENCIA (solo datos validados) y ESCENARIO (simulaciones rotuladas), proyecto vs accionista, deuda, impuestos, capital de trabajo y expansión.",
         que_sabemos=[("RENTABILIDAD DEL PROYECTO = NO CALCULABLE: 0 de 61 corridas publicables.", N),
                      ("No hay un solo bloque económico completo en ninguna configuración: faltan precios, demanda, CAPEX y OPEX.", N),
                      ("El capital necesario no es el CAPEX: el pico de fondos suma arranque y capital de trabajo.", E)],
         dpv=["DPV-001", "DPV-013", "DPV-169", "DPV-178"], dec=["DEC-007", "DEC-084", "DEC-092", "DEC-093"],
         docs=["21_modelo_financiero/guia_ramiro.md", "21_modelo_financiero/conclusiones_financieras.md"], tablas=["21_modelo_financiero/escenarios_financieros.csv"],
         claves="finanzas van tir payback flujo de caja rentabilidad ebitda tasa de descuento deuda dscr"),
    dict(id="riesgos", grupo="riesgos", icono="⚠️", titulo="Riesgos", carpeta="22_riesgos",
         resumen="Qué puede salir mal: sanidad, precios, demanda, tipo de cambio, ejecución, financiamiento.",
         que_es="El registro de riesgos del proyecto y las herramientas para medir qué pasa si algo cambia (sensibilidad, stress, Monte Carlo).",
         por_que="Una decisión que solo es buena en el escenario base es frágil. El riesgo sanitario (influenza aviar) puede cerrar mercados.",
         que_modelamos="34 riesgos cualitativos, sensibilidad de una y dos variables, stress, puntos de quiebre y Monte Carlo (sin distribuciones respaldadas todavía).",
         que_sabemos=[("34 riesgos registrados, todos con probabilidad del proyecto PENDIENTE.", N),
                      ("Monte Carlo del proyecto: NO DISPONIBLE (faltan distribuciones respaldadas).", N),
                      ("Las frecuencias sectoriales (influenza aviar, granos, tipo de cambio) se registran aparte y no son probabilidad del proyecto.", P)],
         dpv=["DPV-180"], dec=["DEC-102"],
         docs=["22_riesgos/guia_ramiro.md", "22_riesgos/registro_riesgos.md"], tablas=["22_riesgos/matriz_riesgos.csv"],
         claves="riesgos sanitario influenza aviar iaap stress sensibilidad monte carlo tipo de cambio"),
    dict(id="optimizador", grupo="riesgos", icono="🎯", titulo="Optimizador", carpeta="22_riesgos",
         resumen="Cómo se comparan las alternativas y por qué «no invertir todavía» es una respuesta válida.",
         que_es="Una herramienta que evalúa todas las combinaciones de arquitectura y escala con el modelo financiero y las ordena según el objetivo que el usuario elige.",
         por_que="No hay «mejor» sin criterio declarado: máximo VAN, menor inversión o menor riesgo pueden dar ganadores distintos.",
         que_modelamos="54 alternativas (5 configuraciones × 4 escalas, 19 variantes, 15 trayectorias), restricciones, robustez, Pareto, dominancia y la alternativa NO_INVERTIR_AUN con reglas explícitas.",
         que_sabemos=[("Con datos reales: OPTIMIZACION_REAL_NO_DISPONIBLE (ninguna alternativa con VAN publicable).", N),
                      ("Qué validar primero: nueve ítems empatados en prioridad 1 (demanda, precios, cronograma, tasa, ramp-up, rendimientos…).", E)],
         dpv=["DPV-086", "DPV-060"], dec=["DEC-097", "DEC-098", "DEC-104"],
         docs=["22_riesgos/guia_ramiro.md", "22_riesgos/conclusiones_riesgo_optimizacion.md"], tablas=["22_riesgos/que_hacer_ahora.csv"],
         claves="optimizador alternativas ranking objetivo pareto robustez no invertir aun"),
    dict(id="crecimiento", grupo="inversion", icono="🌱", titulo="Escala y estrategia de crecimiento", carpeta="23_plan_expansion",
         resumen="Qué significa cada escala y cómo crecer por etapas sin sobredimensionar.",
         que_es="La escala es cuántas aves se faenan por día. La estrategia de crecimiento define qué se construye al inicio y qué se agrega después.",
         por_que="Capacidad no significa que se venda todo: una planta grande sin demanda queda ociosa y una chica puede quedar corta.",
         que_modelamos="Escenarios de 2.500 a 20.000 aves/día, demanda necesaria para llenar cada escala, trayectorias de expansión y gates para avanzar de etapa.",
         que_sabemos=[("Con la evidencia actual ninguna escala está justificada: la utilización respaldada por demanda documentada es 0 %.", E),
                      ("Demanda necesaria para llenar cada escala (ave completa): 4,1 / 8,2 / 16,4 / 32,8 t por día calendario.", E),
                      ("Escala mínima eficiente: dato crítico PENDIENTE (no se concluye que 2.500 sea chica ni 20.000 grande).", N)],
         dpv=["DPV-083"], dec=["DEC-001", "DEC-033"],
         docs=["23_plan_expansion/guia_ramiro.md", "23_plan_expansion/conclusiones_escala.md", "23_plan_expansion/gates_expansion.md"], tablas=[],
         claves="escala crecimiento expansion etapas 2500 5000 10000 20000 aves por dia capacidad gates"),
]

# Cadena avícola visual (¿cómo funciona el negocio?): nodo → módulo y explicación breve (sin números nuevos;
# los números se toman de las fuentes al construir la vista).
CADENA = [
    ("huevo", "Huevo / pollito", "Las reproductoras ponen huevos fértiles; una incubadora los convierte en pollitos de un día.", "incubacion"),
    ("crianza", "Crianza", "El pollito crece ~45–50 días en un galpón hasta ~2,7–3,0 kg.", "produccion"),
    ("alimento", "Alimento", "Mezcla de maíz y soja: el mayor costo y el mayor flujo físico.", "alimento"),
    ("granjas", "Granjas", "Galpones propios o de productores integrados.", "granjas"),
    ("captura", "Captura", "Se retira el alimento, se capturan las aves y se cargan en jaulas.", "transporte_vivo"),
    ("transporte", "Transporte vivo", "Camiones llevan las aves a la planta respetando bienestar y tiempos.", "transporte_vivo"),
    ("faena", "Faena", "Colgado, aturdido, sangrado, escaldado, desplume y eviscerado con inspección veterinaria.", "proceso"),
    ("enfriamiento", "Enfriamiento", "La carcasa se enfría rápido: punto crítico de inocuidad.", "proceso"),
    ("trozado", "Trozado / productos", "Entero, cortes o deshuesado según el mix comercial.", "productos"),
    ("empaque", "Empaque", "Bandejas, bolsas y cajas rotuladas y trazables.", "proceso"),
    ("frio", "Frío", "Cámaras de refrigerado y congelado.", "frio"),
    ("logistica", "Logística", "Camiones refrigerados a clientes o centros de distribución.", "logistica"),
    ("cliente", "Cliente", "Supermercados, mayoristas, gastronomía, industria, carnicerías.", "demanda"),
]
RAMAS = [
    ("subproductos", "Subproductos", "Plumas, sangre, vísceras y cabezas salen todos los días por circuitos separados.", "subproductos", "faena"),
    ("efluentes", "Efluentes", "El agua usada se trata antes de volcarla.", "agua", "faena"),
    ("rendering", "Rendering", "Cocción y secado de subproductos para hacer harinas y grasas (propio solo en CF, futuro).", "subproductos", "faena"),
    ("exportacion", "Exportación", "Partes que valen más afuera, con habilitación por destino.", "exportacion", "frio"),
]

# Ayuda contextual (1–3 frases) de términos que aparecen en pantalla. Definiciones conceptuales estándar.
AYUDAS = {
    "VAN": "Valor actual neto: cuánto valor genera el proyecto por encima de la rentabilidad mínima que le exigís (la tasa de descuento). Positivo = crea valor en ese escenario; negativo = no alcanza esa rentabilidad.",
    "TIR": "Tasa interna de retorno: la rentabilidad anual implícita del flujo de caja del escenario. Se compara con la tasa de descuento. A veces no existe o no es única (flujos que cambian de signo varias veces).",
    "PAYBACK": "Tiempo aproximado para recuperar la inversión con el flujo de caja que genera el proyecto (sin descontar).",
    "EBITDA": "Resultado operativo antes de intereses, impuestos y depreciaciones: ventas netas menos costos operativos. No es caja: no incluye inversiones ni capital de trabajo.",
    "MARGEN EBITDA": "EBITDA dividido por las ventas netas: cuánto queda de cada peso vendido antes de intereses, impuestos y depreciaciones.",
    "DSCR": "Cobertura del servicio de deuda: cuántas veces el flujo disponible cubre lo que hay que pagar de deuda (intereses + amortización) en un período. Menos de 1 = ese período no alcanza sin aportes.",
    "DSCR MÍNIMO": "El DSCR más bajo de todo el horizonte. Si cae en el arranque (ramp-up), cuando la planta todavía no produce a pleno, puede ser muy bajo sin que la deuda sea impagable en régimen.",
    "CAPEX": "Inversión en activos: terreno, edificio, máquinas, frío, galpones, vehículos.",
    "OPEX": "Costos operativos de todos los meses: alimento, pollitos, personal, energía, agua, fletes, mantenimiento.",
    "CAPITAL DE TRABAJO": "Dinero inmovilizado en stock (alimento, aves, producto) y en lo que los clientes todavía no pagaron, menos lo que se debe a proveedores.",
    "FONDOS INICIALES": "Lo que habría que tener antes de operar: CAPEX inicial + capital de trabajo inicial + otros requerimientos de caja.",
    "PICO DE FONDOS": "La máxima necesidad acumulada de caja del proyecto: incluye inversión, arranque con pérdidas y capital de trabajo. Es el capital que habría que tener disponible.",
    "FCR": "Conversión alimenticia: kilos de alimento por kilo de peso vivo. Menor es mejor; gobierna el costo del alimento.",
    "FTE": "Equivalente a tiempo completo: horas de trabajo por día divididas por una jornada de 8 h. Mide carga de trabajo, no cantidad de personas en nómina.",
    "RENDERING": "Proceso de cocción y secado de subproductos no comestibles (plumas, vísceras, sangre, huesos) para obtener harinas y grasa.",
    "FAÇON": "Trabajo hecho por un tercero con cobro de una tarifa: por ejemplo, faenar o fabricar alimento a façon sin tener la planta propia.",
    "RAMP-UP": "Período de arranque: la producción sube de cero a la operación normal; hay menos volumen y más ineficiencias.",
    "ASSET-LIGHT": "Estrategia con pocos activos propios: se terceriza lo que requiere mucha inversión (faena, alimento, granjas).",
    "INTEGRADOS": "Productores que crían los pollos en sus galpones; la empresa les entrega pollito y alimento y les paga por el servicio.",
    "ESCALA": "Cantidad de aves faenadas por día operativo de la planta (2.500 a 20.000 en el estudio). Capacidad no significa ventas.",
    "ROBUSTEZ": "Porcentaje de escenarios de stress y extremos en los que el VAN sigue siendo positivo o nulo. Es determinístico: no es una probabilidad.",
    "SCORE DE RIESGO": "Orden relativo del riesgo entre alternativas (0 = menor). No es una probabilidad.",
    "COBERTURA DE EVIDENCIA": "Qué parte de los bloques del modelo tiene datos reales validados (E1–E3). Hoy es 0 %.",
    "SEMÁFORO": "Verde: evaluable, cumple todo y con evidencia completa. Amarillo: evaluable con evidencia o factibilidad pendiente. Rojo: incumple una restricción obligatoria o un requisito físico. Gris: no evaluable.",
    "PVDP": "Pendiente de verificación documental primaria: el dato se vio en un extracto o en prensa, pero no se leyó el documento original.",
    "DPV": "Dato por validar: un dato que falta y está registrado con su fuente sugerida y responsable.",
    "NO_INVERTIR_AUN": "Alternativa de decisión: no comprometer capital todavía (mantener opciones, validar información). No es un fracaso.",
    "SIMULACIÓN": "Resultado calculado por el motor sobre datos y supuestos que cargó el usuario. No es evidencia ni pronóstico.",
    "EVIDENCIA": "Dato real con fuente identificable y nivel E1–E3. Hoy el proyecto no tiene datos económicos con evidencia.",
    "VENTAS": "Toneladas vendidas en el último año del horizonte (nunca más que lo producido ni que la demanda cargada).",
    "FACTURACIÓN": "Kilos vendidos por precio, antes de descuentos y bonificaciones.",
    "TASA DE DESCUENTO": "La rentabilidad mínima anual que se le exige al proyecto para considerar que crea valor.",
    "CMS": "Carne separada mecánicamente: pasta de carne recuperada de carcasas, usada por la industria de embutidos.",
    "HALAL": "Certificación de faena según la ley islámica, exigida por algunos destinos de exportación (Golfo).",
    "SENASA": "Servicio Nacional de Sanidad y Calidad Agroalimentaria: habilita plantas, inspecciona la faena y certifica exportaciones.",
}

# Estados técnicos → frase en castellano (el código queda como dato secundario).
ESTADOS = {
    "NO_CALCULABLE": "No se puede calcular todavía porque faltan datos.",
    "NO_CALCULABLE_REGLA_FISCAL_PENDIENTE": "No se puede calcular todavía porque falta definir el tratamiento fiscal (ingresos brutos por mercado).",
    "NO_PUBLICABLE_POR_EVIDENCIA_INSUFICIENTE": "No se publica porque no hay evidencia real suficiente.",
    "NO_DISPONIBLE_FALTAN_INPUTS_DEL_ESCENARIO": "No disponible: el escenario no tiene todos los datos necesarios.",
    "OPTIMIZACION_REAL_NO_DISPONIBLE": "Todavía no se puede elegir una alternativa con datos reales: ninguna tiene rentabilidad calculable.",
    "MEJOR_EN_ESCENARIO": "Hay una alternativa que mejor cumple el objetivo dentro de esta simulación.",
    "NINGUNA_CONFIGURACION_FACTIBLE": "Ninguna alternativa de inversión cumple las condiciones del escenario.",
    "NO_INVERTIR_AUN": "Con estos datos, la regla de decisión indica no comprometer capital todavía.",
    "PESOS_NO_DEFINIDOS": "Falta definir cuánto pesa cada criterio del objetivo balanceado.",
    "SIN_INVERSION": "Con estos datos, la regla de decisión indica no comprometer capital todavía.",
    "TIR_AMBIGUA": "La TIR no es única: el flujo cambia de signo varias veces.",
    "NO_EXISTE": "La TIR no existe para este flujo de caja.",
    "NO_CALCULADA": "No se calculó en esta vista (modo rápido).",
    "NO_RECUPERADO": "La inversión no se recupera dentro del horizonte.",
    "NO_APLICA": "No aplica a esta alternativa.",
    "PENDIENTE": "Pendiente: todavía no hay dato.",
    "FACTIBILIDAD_PENDIENTE": "No se sabe todavía si es físicamente factible (faltan datos del sitio).",
    "FACTIBLE": "Físicamente factible con los datos declarados.",
    "NO_FACTIBLE": "No es físicamente factible con los datos declarados.",
    "OVERRIDE_INCOMPATIBLE_CON_ARQUITECTURA": "Los montos cargados no corresponden a la arquitectura elegida.",
    "SIMULACION_HIPOTETICA_NO_VALIDADA": "Simulación hipotética: no es un dato real.",
    "SIMULACION_HIPOTETICA_OVERRIDE_TOTAL": "Simulación con montos sin verificar contra la arquitectura.",
    "CASO_PRUEBA_ARTIFICIAL_NO_ES_PROYECTO": "Caso de demostración con datos ficticios: no es el proyecto.",
    "COMPARABILIDAD_FALSE": "No se puede comparar con las demás (faltan datos o tiene otra base).",
    "NO_EJECUTADO_VALORES_PENDIENTES": "No se ejecutó: falta la magnitud del cambio.",
    "NO_DISPONIBLE_POR_FALTA_DE_DISTRIBUCIONES": "No disponible: faltan distribuciones de probabilidad respaldadas.",
    "ENCONTRADO": "Se encontró el punto de quiebre.",
    "NO_ENCONTRADO_EN_RANGO": "No hay quiebre dentro del rango evaluado.",
    "DECISION_NO_ROBUSTA": "La ganadora cambia en algunos escenarios de stress: la decisión no es robusta.",
    "ROBUSTA_EN_ESCENARIOS_EVALUADOS": "La ganadora se mantiene en los escenarios evaluados.",
    "ERROR_CONSTRUCCION": "El motor no pudo armar esta alternativa con los datos cargados.",
}
